driver.add_cookie(
driver.application_cache
driver.back(
driver.capabilities
driver.close(
driver.command_executor
driver.create_options(
driver.create_web_element(
driver.current_url
driver.current_window_handle
driver.delete_all_cookies(
driver.delete_cookie(
driver.desired_capabilities
driver.error_handler
driver.execute(
driver.execute_async_script(
driver.execute_cdp_cmd(
driver.execute_script(
driver.file_detector
driver.file_detector_context(
driver.find_element(
driver.find_element_by_class_name(
driver.find_element_by_css_selector(
driver.find_element_by_id(
driver.find_element_by_link_text(
driver.find_element_by_name(
driver.find_element_by_partial_link_text(
driver.find_element_by_tag_name(
driver.find_element_by_xpath(
driver.find_elements(
driver.find_elements_by_class_name(
driver.find_elements_by_css_selector(
driver.find_elements_by_id(
driver.find_elements_by_link_text(
driver.find_elements_by_name(
driver.find_elements_by_partial_link_text(
driver.find_elements_by_tag_name(
driver.find_elements_by_xpath(
driver.forward(
driver.fullscreen_window(
driver.get(
driver.get_cookie(
driver.get_cookies(
driver.get_log(
driver.get_network_conditions(
driver.get_screenshot_as_base64(
driver.get_screenshot_as_file(
driver.get_screenshot_as_png(
driver.get_window_position(
driver.get_window_rect(
driver.get_window_size(
driver.implicitly_wait(
driver.launch_app(
driver.log_types
driver.maximize_window(
driver.minimize_window(
driver.mobile
driver.name
driver.orientation
driver.page_source
driver.quit(
driver.refresh(
driver.save_screenshot(
driver.service
driver.session_id
driver.set_network_conditions(
driver.set_page_load_timeout(
driver.set_script_timeout(
driver.set_window_position(
driver.set_window_rect(
driver.set_window_size(
driver.start_client(
driver.start_session(
driver.stop_client(
driver.switch_to
driver.switch_to_active_element(
driver.switch_to_alert(
driver.switch_to_default_content(
driver.switch_to_frame(
driver.switch_to_window(
driver.title
driver.w3c
driver.window_handles
